"""Base strategy interface."""

from __future__ import annotations

import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal
from typing import TYPE_CHECKING

from tsxbot.constants import OrderType, SignalDirection

if TYPE_CHECKING:
    from tsxbot.config_loader import AppConfig
    from tsxbot.data.bars import Bar
    from tsxbot.data.market_data import Tick
    from tsxbot.time.session_manager import SessionManager

logger = logging.getLogger(__name__)


@dataclass
class TradeSignal:
    """Trading signal generated by strategy."""

    symbol: str
    direction: SignalDirection
    timestamp: datetime

    # Entry details
    quantity: int = 1
    entry_type: OrderType = OrderType.MARKET
    limit_price: Decimal | None = None

    # Bracket details (optional overrides, otherwise config default)
    stop_ticks: int | None = None
    target_ticks: int | None = None

    reason: str = ""


class BaseStrategy(ABC):
    """Abstract base class for all strategies."""

    def __init__(self, config: AppConfig, session_manager: SessionManager):
        """
        Initialize strategy.

        Args:
            config: Full application configuration object.
            session_manager: Session manager for time/RTH checks.
        """
        self.config = config
        self.session = session_manager
        self.logger = logger.getChild(self.__class__.__name__)

    @abstractmethod
    def on_tick(self, tick: Tick) -> list[TradeSignal]:
        """Process new tick data."""
        pass

    @abstractmethod
    def on_bar(self, bar: Bar) -> list[TradeSignal]:
        """Process new bar data (e.g. 1-minute bar)."""
        pass

    @abstractmethod
    def reset(self) -> None:
        """Reset strategy state (e.g. for new trading session)."""
        pass
